### ISSUE TITLE
Publisering av ontologiene i maskinlesbart format

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/dqv-ap-no#1]
- [x] [dqvno](https://github.com/Informasjonsforvaltning/dqv-ap-no/blob/review/ontology/dqvno/dqvno-turtle.ttl) med URI data.norge.no/vocabulary/dqvno#

**Comment by stigbd** [comment]
Skal sette meg inn i https://www.w3.org/TR/swbp-vocab-pub/ via https://linkingresearch.wordpress.com/2013/05/27/how-to-properly-publish-a-vocabulary-or-ontology-in-the-web-1-of-6/

**Comment by stigbd** [comment]
Denne:
https://figshare.com/articles/How_to_properly_publish_a_vocabulary_or_ontology_in_the_web/881824

**Comment by jimjyang** [comment]
Kan hende at ontologien for en spesifikasjon (i dette tilfelle dqv-ap-no) ikke trenger å publiseres på data.norge.no siden den kan betraktes som "supporting document", og at det holder å ha den i github?

**Comment by stigbd** [comment]
Implementert og bestilt publisering

**Comment by jimjyang** [comment]
Publisert.
