### ISSUE TITLE
Html, captions: oversettes automatisk til norsk

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/dqv-ap-no#10]
Figure -> Figur, Table -> Tabell, osv. 
Se på :include shared/translation.adoc.

**Comment by stigbd** [comment]
Fins det eit eksempel på ein asciidoc publikasjon frå oss der dette faktisk fungerer?

**Comment by stigbd** [comment]
Då har eg fiksa oversettelse til bokmål for html og pdf. (Epub ser ikkje ut til å fungere.) Fint om du verifiserer og lukker issue, @jimjyang

**Comment by jimjyang** [comment]
Ser fint ut. Lukkes.
