### ISSUE TITLE
EPUB flere feil

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/dqv-ap-no#12]
I tillegg de to nevnt i https://github.com/Informasjonsforvaltning/forvaltningsstandard-begrepskoordinering/issues/10: 

[ ] De to punktumene i multiplisitet er litt bare ett punktum, f.eks. 1.n istedenfor 1..n.

**Comment by jimjyang** [comment]
@stigbd Skal vi lukke denne? Vi publiserer nå ikke EPUB.

**Comment by stigbd** [comment]
Ja, det synes eg vi skal lukke. Etter å ha gitt label wontfix.

**Comment by jimjyang** [comment]
wontfix
