### ISSUE TITLE
[publisering] PDF-filnavnet bør gjenspeile spesifikasjonens navn

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/dqv-ap-no#71]
Navnet til PDF-filen som kan lastes ned er nå "document.pdf". 

Ønsker å ha et filnavn som gjenspeile spesifikasjonens navn, f.eks. repo-navnet (som også brukes i URLen til den gjeldende versjonen på data.norge.no).

**Comment by stigbd** [comment]
Fiksa i 845e50e1b444bd5f085ab24dcd30171279aa52d7

**Comment by jimjyang** [comment]
Fiksa
